# Usa una imagen base de Node.js
FROM node:18


# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Expone el puerto en el que la aplicación se ejecuta
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["npm", "start"]